config/routes.rb
Urgentcy::Application.routes.draw do

  ActiveAdmin.routes(self)
  resources :bookings
  resources :locations
  resources :medical_conditions
  resources :patients
  resources :surgeons
  resources :surgical_procedures
  resources :surgical_specialties
  resources :urgency_categories

  devise_for :users

  scope "static_pages", controller: :static_pages do
    get "/home" => :home, as: :home_page
    get "/help" => :help, as: :help_page
    get "/about" => :about, as: :about_page
  end

  get 'patients_search/' => 'patients#search', defaults: {format: :json}

  root to: "static_pages#home"
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :location
  belongs_to :patient
  belongs_to :surgeon
  belongs_to :surgical_procedure
  belongs_to :surgical_specialty
  belongs_to :urgency_category

  accepts_nested_attributes_for :patient


end

app/models/location.rb
class Location < ActiveRecord::Base
  has_paper_trail on: [:update, :destroy]

  has_many :bookings
end

app/models/medical_condition.rb
class MedicalCondition < ActiveRecord::Base
  has_paper_trail on: [:update, :destroy]

  has_many :patient_medical_conditions
  has_many :patients, through: :patient_medical_conditions

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_paper_trail on: [:update, :destroy]
  
  has_many :patient_medical_conditions
  has_many :medical_conditions, through: :patient_medical_conditions

  has_many :bookings

  validates_uniqueness_of :mrn

  def age
    #TODO What if they are less than 1? should show months / weeks / days
    ((Time.now.to_time - date_of_birth.to_time) / 1.years).to_i unless date_of_birth.nil?
  end

  def combined_details
    "#{last_name}, #{first_name} - #{mrn}"
  end

end

app/models/patient_medical_condition.rb
class PatientMedicalCondition < ActiveRecord::Base
  has_paper_trail on: [:update, :destroy, :create]

  belongs_to :patient
  belongs_to :medical_condition
end

app/models/surgeon.rb
class Surgeon < ActiveRecord::Base
  has_paper_trail on: [:update, :destroy]

  has_many :bookings

  def full_name
    "#{last_name}, #{first_name}"
  end
end

app/models/surgical_procedure.rb
class SurgicalProcedure < ActiveRecord::Base
  has_paper_trail on: [:update, :destroy]

  validates_uniqueness_of :name

  has_many :bookings
end

app/models/surgical_specialty.rb
class SurgicalSpecialty < ActiveRecord::Base
  has_paper_trail on: [:update, :destroy]

  validates_uniqueness_of :name

  has_many :bookings
end

app/models/urgency_category.rb
class UrgencyCategory < ActiveRecord::Base
  has_paper_trail on: [:update, :destroy]

  has_many :bookings

  def time_in_minutes
    (acceptable_wait_hours * 60) + acceptable_wait_minutes
  end

  def time_in_hours
    time_in_minutes / 60
  end

  def urgency_in_words
    "#{name} - #{acceptable_wait_hours} hours #{acceptable_wait_minutes} minutes"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name

  def full_name
    "#{self.last_name}, #{self.first_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name]
  end

  def authenticate_admin_user!
    redirect_to new_user_session_path unless current_user.admin?
  end

end

app/controllers/bookings_controller.rb
class BookingsController < InheritedResources::Base
  before_filter :authenticate_user!
  respond_to :html, :json



  private

  def resource_params
    return [] if request.get?
    [params.require(:booking).permit!]
  end
end

app/controllers/locations_controller.rb
class LocationsController < InheritedResources::Base
  respond_to :html, :json

end

app/controllers/medical_conditions_controller.rb
class MedicalConditionsController < InheritedResources::Base
  respond_to :html, :json

  private

  def resource_params
    return [] if request.get?
    [ params.require(:medical_condition).permit! ]
  end

end

app/controllers/patients_controller.rb
class PatientsController < InheritedResources::Base
  before_filter :authenticate_user!
  respond_to :html, :json

  def search
    if params[:mrn]
      #@patients = Patient.where(mrn: params[:mrn])
      @patients = Patient.where("mrn LIKE '%#{params[:mrn]}%'")
    elsif params[:last_name]
      @patients = Patient.where(last_name: params[:last_name])
    elsif params[:first_name]
      @patients = Patient.where(first_name: params[:first_name])
    else
      @patients = Patient.all
    end
    respond_with patients: @patients
  end

  private


  def resource_params
    return [] if request.get?
    [params.require(:patient).permit!]
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

end

app/controllers/surgeons_controller.rb
class SurgeonsController < InheritedResources::Base
  respond_to :html, :json
  private

  def resource_params
    return [] if request.get?
    [ params.require(:surgeon).permit! ]
  end

end

app/controllers/surgical_procedures_controller.rb
class SurgicalProceduresController < InheritedResources::Base
  respond_to :html, :json
  private

  def resource_params
    return [] if request.get?
    [ params.require(:surgical_procedure).permit! ]
  end
end

app/controllers/surgical_specialties_controller.rb
class SurgicalSpecialtiesController < InheritedResources::Base
  respond_to :html, :json
  private

  def resource_params
    return [] if request.get?
    [ params.require(:surgical_specialty).permit! ]
  end
end

app/controllers/urgency_categories_controller.rb
class UrgencyCategoriesController < InheritedResources::Base
  respond_to :html, :json
  private

  def resource_params
    return [] if request.get?
    [ params.require(:urgency_category).permit! ]
  end

  def build_resource_params
    [params.require(:urgency_category)]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  ALERT_DIV = {
      notice: 'alert alert-info',
      success: 'alert alert-success',
      error: 'alert alert-danger',
      alert: 'alert alert-danger'
  }

  def flash_messages
    flash_messages = []
    flash.each do |type, message|
      next if message.blank?

      Array(message).each do |msg|

        text = %Q[<div class="alert-block "> <div class="fade in #{ALERT_DIV[type]}">
          <button class="close" data-dismiss="alert">X</button>
            <p>#{msg}</p>
          </div>
        </div>
        ]
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end

  def error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-block alert-danger">
      <h2>#{sentence}</h2>
      <ul class="list-unstyled">#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

end

app/views/bookings/new.html.erb
<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2>New booking request</h2>
    </div>
    <div class="panel-body">

      <%= form_for @booking, html: {role: 'form', class: 'form-horizontal'} do |b| %>
          <fieldset>
            <legend>Patient</legend>
            <h3>Select patient from list or register a new patient below</h3>

            <div class="form-group">
              <%= b.label :mrn, 'MRN', class: 'col-lg-2 col-sm-2 control-label' %>
              <div class="col-lg-6 col-sm-4 col-xs-12">
                <%= text_field_tag :mrn, nil, class: 'form-control mrn-picker' %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-lg-offset-2 col-lg-6 col-sm-4 col-xs-12">
                <a data-toggle="modal" href="#new_patient_modal" class="btn btn-primary btn-lg">Register new patient</a>
              </div>
            </div>
          </fieldset>
          <fieldset>
            <legend>Booking</legend>

            <div class="form-group">
              <%= b.label :urgency, class: 'col-lg-2 col-sm-2 control-label' %>
              <div class="col-lg-6 col-sm-4 col-xs-12">
                <%= b.collection_select :urgency_category_id, UrgencyCategory.all, :id, :urgency_in_words, {}, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <%= b.label :surgeon, class: 'col-lg-2 col-sm-2 control-label' %>
              <div class="col-lg-6 col-sm-4 col-xs-12">
                <%= b.collection_select :surgeon_id, Surgeon.order(:last_name), :id, :full_name, {}, class: 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <%= b.label :planned_procedure, class: 'col-lg-2 col-sm-2 control-label' %>
              <div class="col-lg-6 col-sm-4 col-xs-12">
                <%= b.collection_select :surgical_procedure_id, SurgicalProcedure.all, :id, :name, {}, class: 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <%= b.label :specialty, class: 'col-lg-2 col-sm-2 control-label' %>
              <div class="col-lg-6 col-sm-4 col-xs-12">
                <%= b.collection_select :surgical_specialty_id, SurgicalSpecialty.all, :id, :name, {}, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <%= b.label :required_hours, class: 'col-lg-2 col-sm-2 control-label' %>
              <div class="col-lg-2 col-sm-2 col-xs-12">
                <%= b.number_field :required_hours, class: 'form-control' %>
              </div>
              <%= b.label :required_minutes, class: 'col-lg-2 col-sm-2 control-label' %>
              <div class="col-lg-2 col-sm-2 col-xs-12">
                <%= b.number_field :required_minutes, class: 'form-control', step: 5, min: 0, max: 55 %>
              </div>
            </div>
            <div class="form-group">
              <%= b.label :notice_required, class: 'col-lg-2 col-sm-2 control-label' %>
              <div class="col-lg-6 col-sm-6 col-xs-12">
                <%= b.text_field :notice_required, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <%= b.label :availability, class: 'col-lg-2 col-sm-2 control-label' %>
              <div class="col-lg-6 col-sm-6 col-xs-12">
                <%= b.text_field :availability, class: 'form-control' %>
              </div>
            </div>
          </fieldset>
          <div class="form-group">
            <div class="col-lg-offset-2 col-lg-6 col-sm-4 col-xs-12">
              <%= b.submit 'Send request', class: 'btn btn-default' %>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>



<%= render 'patients/new_patient_modal' %>

app/views/patients/_form.html.erb
<%= form_for @patient, html: {role: 'form', class: 'form-horizontal'} do |f| %>
    <div class="form-group">
      <%= f.label :mrn, class: 'col-lg-2 col-sm-2 control-label' %>
      <div class="col-lg-6 col-sm-4 col-xs-12">
        <%= f.text_field :mrn, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :last_name, class: 'col-lg-2 col-sm-2 control-label' %>
      <div class="col-lg-6 col-sm-4 col-xs-12">
        <%= f.text_field :last_name, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :first_name, class: 'col-lg-2 col-sm-2 control-label' %>
      <div class="col-lg-6 col-sm-4 col-xs-12">
        <%= f.text_field :first_name, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :date_of_birth, class: 'col-lg-2 col-sm-2 control-label' %>
      <div class="col-lg-6 col-sm-4 col-xs-12">
        <div class="date-picker"></div>
        <%= f.hidden_field :date_of_birth  %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :ward_location, class: 'col-lg-2 col-sm-2 control-label' %>
      <div class="col-lg-6 col-sm-4 col-xs-12">
        <%= f.text_field :ward_location, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-6 col-sm-4 col-xs-12">
        <%= f.submit 'Save', class: 'btn btn-default' %>
      </div>
    </div>
<% end %>

app/views/patients/_new_patient_modal.html.erb
<div class="modal fade" id="new_patient_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">New patient</h4>
      </div>
      <div class="modal-body">
        <%= form_for Patient.new, html: {role: 'form', id: 'new_patient_form', class: 'form-horizontal'} do |p| %>
            <div class="form-group">
              <%= p.label :last_name, class: 'col-lg-2 col-sm-2 control-label' %>
              <div class="col-lg-10 col-sm-10 col-xs-12">
                <%= p.text_field :last_name, class: 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <%= p.label :first_name, class: 'col-lg-2 col-sm-2 control-label' %>
              <div class="col-lg-10 col-sm-10 col-xs-12">
                <%= p.text_field :first_name, class: 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <%= p.label :mrn, class: 'col-lg-2 col-sm-2 control-label' %>
              <div class="col-lg-10 col-sm-10 col-xs-12">
                <%= p.text_field :mrn, class: 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <%= p.label :date_of_birth, class: 'col-lg-2 col-sm-2 control-label' %>
              <div class="col-lg-6 col-sm-4 col-xs-12">
                <div class="date-picker">
                  <%= p.hidden_field :date_of_birth, class: 'form-control' %>
                </div>
              </div>
            </div>

            <div class="form-group">
              <%= p.label :ward_location, class: 'col-lg-2 col-sm-2 control-label' %>
              <div class="col-lg-10 col-sm-10 col-xs-12">
                <%= p.text_field :ward_location, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <p class="col-lg-2 col-sm-2 control-label" id="status"></p>
            </div>

            </div>
            <div class="modal-footer">
                <button type="submit" name="commit" class="btn btn-success col-lg-offset-4 col-sm-offset-4" id="save_patient">Save patient</button>
                <button type="submit" name="commit" class="btn btn-success col-lg-offset-4 col-sm-offset-4" id="close_modal" data-dismiss="modal">Close Window</button>
            </div>
        <% end %>
        </div>
  </div>
</div>

app/views/patients/edit.html.erb
<h1>Edit Patient</h1>
<%= render 'form' %>

app/views/patients/index.html.erb
<div class="col-lg-10">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Patient index</h3>
    </div>
    <div class="panel-body">
      <table class="table table-striped table-hover table-responsive">
        <thead>
        <tr>
          <th>Last name</th>
          <th>First name</th>
          <th>MRN</th>
          <th>Date of Birth</th>
          <th>Ward location</th>
        </tr>
        </thead>
        <tbody>
        <% @patients.each do |p| %>
            <tr>
              <td><%= link_to p.last_name, patient_path(p) %></td>
              <td><%= link_to p.first_name, patient_path(p) %></td>
              <td><%= p.mrn %></td>
              <td><%= p.date_of_birth %></td>
              <td><%= p.ward_location %></td>
            </tr>
        <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/patients/new.html.erb
<h1>Register New Patient</h1>
<%= render 'form' %>

app/views/patients/show.html.erb
<div class="col-lg-8">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1 class="panel-title">Patient details</h1>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-lg-6">
          <dl class="dl-horizontal">
            <dt>Last name</dt>
            <dd><%= @patient.last_name %></dd>
            <dt>First name</dt>
            <dd><%= @patient.first_name %></dd>
            <dt>MRN</dt>
            <dd><%= @patient.mrn %></dd>
            <dt>Date of Birth</dt>
            <dd><%= @patient.date_of_birth %></dd>
            <dt>Age</dt>
            <dd><%= @patient.age %></dd>
          </dl>
        </div>


        <div class="col-lg-6">
          <p class="">Medical conditions <span class="badge"><%= @patient.medical_conditions.count %></span></p>
          <ul>
            <% @patient.medical_conditions.each do |mc| %>
                <li><%= mc.name %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_github_buttons.html.erb
<div class="bs-social">
  <ul class="bs-social-buttons">
    <li>
      <iframe src="http://ghbtns.com/github-btn.html?user=mfeckie&repo=urgentcy&type=watch&count=true"
              allowtransparency="true" frameborder="0" scrolling="0" width="110" height="20"></iframe>
    </li>
    <li>
      <iframe src="http://ghbtns.com/github-btn.html?user=mfeckie&repo=urgentcy&type=fork&count=true"
              allowtransparency="true" frameborder="0" scrolling="0" width="95" height="20"></iframe>
    </li>
    <li>

    </li>
  </ul>
</div>

app/views/static_pages/about.html.erb
<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2>About Urgentcy</h2>
    </div>
    <div class="panel-body">
      <h3>Urgentcy is</h3>

      <p>An open source project licensed under <span><a href="http://www.mozilla.org/MPL/2.0/">Mozilla Public License
        2.0</a><%= image_tag 'osi_standard_logo.png', class: "img-osilogo" %></span></p>


      <h3>Data security and confidentiality</h3>

      <p>In order to make a booking or access any patient information you will need to have an account and be signed
        in.</p>

      <p>All updates and deletions of patient data or bookings is logged to the database and are tracked to the users
        who took the action</p>

    </div>
    <%= render :partial => 'github_buttons' %>
  </div>
</div>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>

<p>Find me in app/views/static_pages/help.html.erb</p>