config/routes.rb
Urgentcy::Application.routes.draw do

  ActiveAdmin.routes(self)
  resources :bookings
  resources :locations
  resources :medical_conditions
  resources :patients
  resources :surgeons
  resources :surgical_procedures
  resources :surgical_specialties
  resources :urgency_categories

  devise_for :users

  scope "static_pages", controller: :static_pages do
    get "/home" => :home, as: :home_page
    get "/help" => :help, as: :help_page
    get "/about" => :about, as: :about_page
  end

  get 'patients_search/' => 'patients#search', defaults: {format: :json}

  root to: "static_pages#home"
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :location
  belongs_to :patient
  belongs_to :surgeon
  belongs_to :surgical_procedure
  belongs_to :surgical_specialty
  belongs_to :urgency_category

  accepts_nested_attributes_for :patient


end

app/models/location.rb
class Location < ActiveRecord::Base
  has_paper_trail on: [:update, :destroy]

  has_many :bookings
end

app/models/medical_condition.rb
class MedicalCondition < ActiveRecord::Base
  has_paper_trail on: [:update, :destroy]

  has_many :patient_medical_conditions
  has_many :patients, through: :patient_medical_conditions

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_paper_trail on: [:update, :destroy]
  
  has_many :patient_medical_conditions
  has_many :medical_conditions, through: :patient_medical_conditions

  has_many :bookings

  validates_uniqueness_of :mrn

  def age
    #TODO What if they are less than 1? should show months / weeks / days
    ((Time.now.to_time - date_of_birth.to_time) / 1.years).to_i unless date_of_birth.nil?
  end

  def combined_details
    "#{last_name}, #{first_name} - #{mrn}"
  end

end

app/models/patient_medical_condition.rb
class PatientMedicalCondition < ActiveRecord::Base
  has_paper_trail on: [:update, :destroy, :create]

  belongs_to :patient
  belongs_to :medical_condition
end

app/models/surgeon.rb
class Surgeon < ActiveRecord::Base
  has_paper_trail on: [:update, :destroy]

  has_many :bookings

  def full_name
    "#{last_name}, #{first_name}"
  end
end

app/models/surgical_procedure.rb
class SurgicalProcedure < ActiveRecord::Base
  has_paper_trail on: [:update, :destroy]

  validates_uniqueness_of :name

  has_many :bookings
end

app/models/surgical_specialty.rb
class SurgicalSpecialty < ActiveRecord::Base
  has_paper_trail on: [:update, :destroy]

  validates_uniqueness_of :name

  has_many :bookings
end

app/models/urgency_category.rb
class UrgencyCategory < ActiveRecord::Base
  has_paper_trail on: [:update, :destroy]

  has_many :bookings

  def time_in_minutes
    (acceptable_wait_hours * 60) + acceptable_wait_minutes
  end

  def time_in_hours
    time_in_minutes / 60
  end

  def urgency_in_words
    "#{name} - #{acceptable_wait_hours} hours #{acceptable_wait_minutes} minutes"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name

  def full_name
    "#{self.last_name}, #{self.first_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name]
  end

  def authenticate_admin_user!
    redirect_to new_user_session_path unless current_user.admin?
  end

end

app/controllers/bookings_controller.rb
class BookingsController < InheritedResources::Base
  before_filter :authenticate_user!
  respond_to :html, :json



  private

  def resource_params
    return [] if request.get?
    [params.require(:booking).permit!]
  end
end

app/controllers/locations_controller.rb
class LocationsController < InheritedResources::Base
  respond_to :html, :json

end

app/controllers/medical_conditions_controller.rb
class MedicalConditionsController < InheritedResources::Base
  respond_to :html, :json

  private

  def resource_params
    return [] if request.get?
    [ params.require(:medical_condition).permit! ]
  end

end

app/controllers/patients_controller.rb
class PatientsController < InheritedResources::Base
  before_filter :authenticate_user!
  respond_to :html, :json

  def search
    if params[:mrn]
      #@patients = Patient.where(mrn: params[:mrn])
      @patients = Patient.where("mrn LIKE '%#{params[:mrn]}%'")
    elsif params[:last_name]
      @patients = Patient.where(last_name: params[:last_name])
    elsif params[:first_name]
      @patients = Patient.where(first_name: params[:first_name])
    else
      @patients = Patient.all
    end
    respond_with patients: @patients
  end

  private


  def resource_params
    return [] if request.get?
    [params.require(:patient).permit!]
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

end

app/controllers/surgeons_controller.rb
class SurgeonsController < InheritedResources::Base
  respond_to :html, :json
  private

  def resource_params
    return [] if request.get?
    [ params.require(:surgeon).permit! ]
  end

end

app/controllers/surgical_procedures_controller.rb
class SurgicalProceduresController < InheritedResources::Base
  respond_to :html, :json
  private

  def resource_params
    return [] if request.get?
    [ params.require(:surgical_procedure).permit! ]
  end
end

app/controllers/urgency_categories_controller.rb
class UrgencyCategoriesController < InheritedResources::Base
  respond_to :html, :json
  private

  def resource_params
    return [] if request.get?
    [ params.require(:urgency_category).permit! ]
  end

  def build_resource_params
    [params.require(:urgency_category)]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  ALERT_DIV = {
      notice: 'alert alert-info',
      success: 'alert alert-success',
      error: 'alert alert-danger',
      alert: 'alert alert-danger'
  }

  def flash_messages
    flash_messages = []
    flash.each do |type, message|
      next if message.blank?

      Array(message).each do |msg|

        text = %Q[<div class="alert-block "> <div class="fade in #{ALERT_DIV[type]}">
          <button class="close" data-dismiss="alert">X</button>
            <p>#{msg}</p>
          </div>
        </div>
        ]
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end

  def error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-block alert-danger">
      <h2>#{sentence}</h2>
      <ul class="list-unstyled">#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

end

app/views/layouts/_footer.html.erb
<footer class="bs-footer" role="contentinfo">
  <div class="container">
    <p><%= image_tag 'osi_standard_logo.png', class: "img-osilogo" %>Code licensed under <a href="http://www.mozilla.org/MPL/2.0/">Mozilla Public License 2.0</a></p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-collapse navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a  href="<%= home_page_path %>"><%= image_tag 'urgentcy-small.png', alt: 'urgentcy logo', class: 'img-urgentcy-navbar-logo' %></a>
  </div>

  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><a href="#">View waitlist</a></li>
      <li class="dropdown">
        <a class="dropdown-toggle" href="#" data-toggle="dropdown">Bookings<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Make a booking', new_booking_path %></li>
        </ul>
      </li>
      <li class="dropdown">
        <a class="dropdown-toggle" href="#" data-toggle="dropdown">Patients <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Show all patients', patients_path %></li>
          <li><%= link_to 'Register new patient', new_patient_path %></li>
        </ul>
      </li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? && current_user.admin? %>
          <li>
            <%= link_to 'Admin', admin_root_path %>
          </li>
      <% end %>

      <li>
        <a class="dropdown-toggle" href="#" data-toggle="dropdown">My Account<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <% if user_signed_in? %>
              <li><%= link_to 'My account', edit_user_registration_path %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          <% else %>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </li>
    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrgentCY</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-10">
    <%= flash_messages %>
    <%= yield %>
  </div>
</div>


<%= render 'layouts/footer' %>
</body>
</html>